Remove hardcoded output path /var/spool/cwl
ICGC-TCGA-PanCancer/pcawg_delly_workflow pull request #14
Opened 2019-03-14 01:20 UTC by junjun-zhang

2019-03-14 01:29 UTC, junjun-zhang commented
One thing similar to Sanger, the docker build fails at quay.io although the PR itself did not change anything in the Dockerfile. We use other way to build the docker image with the updated files included in the new image.

2019-03-14 14:36 UTC, denis-yuen requested changes
Please update https://github.com/ICGC-TCGA-PanCancer/pcawg_delly_workflow/blob/develop/delly_docker/Dockstore.json accordingly (may need to upload new bai files to portal if they need to be provided as input)

2019-03-15 00:24 UTC, junjun-zhang commented
> Please update https://github.com/ICGC-TCGA-PanCancer/pcawg_delly_workflow/blob/develop/delly_docker/Dockstore.json accordingly (may need to upload new bai files to portal if they need to be provided as input)

There seems to be a misunderstanding here, secondary file defined in CWL does not need to be specified in the job json file itself. CWL runner just assumes the secondary will exist and be named as `<main_file_name>.bai`. No need to change job json.

As for the .bai files, yes, they are already in there same place as the .bam files and named as `<bam_file_name>.bai`. See here: https://dcc.icgc.org/releases/PCAWG/reference_data/data_for_testing/HCC1143_ds.

2019-03-15 14:16 UTC, denis-yuen approved these changes

2019-03-16 20:18 UTC, merged